# Generated by Django 4.1.1 on 2022-10-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitals_BS', '0003_alter_blood_sugar_date_alter_blood_sugar_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_sugar',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='blood_sugar',
            name='sugar',
            field=models.IntegerField(default=None),
        ),
    ]
