# Generated by Django 4.1.1 on 2022-10-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitals_Weight', '0002_weight_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateField(),
        ),
    ]
