# Generated by Django 4.1.1 on 2022-10-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitals_Weight', '0003_alter_weight_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.IntegerField(default=None),
        ),
    ]
