# Generated by Django 4.1.1 on 2022-10-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitals_Weight', '0004_alter_weight_date_alter_weight_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='comments',
            field=models.TextField(default=None, max_length=999),
        ),
    ]
