# Generated by Django 4.1.1 on 2022-10-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitals_Weight', '0005_alter_weight_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='comments',
            field=models.TextField(max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
