# Generated by Django 4.1.1 on 2022-10-01 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('strength', models.IntegerField()),
                ('class_of_medication', models.TextField(max_length=999)),
                ('time_taking1', models.TimeField()),
                ('time_taking2', models.TimeField()),
                ('time_taking3', models.TimeField()),
                ('time_taking4', models.TimeField()),
                ('comments', models.TextField(max_length=999)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
