# Generated by Django 4.1.1 on 2022-10-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='time_taking1',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medications',
            name='time_taking2',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medications',
            name='time_taking3',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medications',
            name='time_taking4',
            field=models.TimeField(auto_now=True),
        ),
    ]
