# Generated by Django 4.1.1 on 2022-10-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medications', '0004_alter_medications_comments_alter_medications_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='time_taking2',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medications',
            name='time_taking3',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medications',
            name='time_taking4',
            field=models.TimeField(null=True),
        ),
    ]
