# Generated by Django 4.1.1 on 2022-10-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_alter_food_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrates',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='food',
            name='comments',
            field=models.TextField(default=None, max_length=999),
        ),
        migrations.AlterField(
            model_name='food',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default=None, max_length=99),
        ),
        migrations.AlterField(
            model_name='food',
            name='servings',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugar',
            field=models.IntegerField(default=None),
        ),
    ]
