# Generated by Django 4.1.1 on 2022-10-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitals_HR', '0003_alter_heart_rate_date_alter_heart_rate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart_rate',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='heart_rate',
            name='heart_rate',
            field=models.IntegerField(default=None),
        ),
    ]
