# Generated by Django 4.1.1 on 2022-10-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitals_BP', '0002_blood_pressure_date_blood_pressure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_pressure',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blood_pressure',
            name='time',
            field=models.TimeField(),
        ),
    ]
