# Generated by Django 4.1.1 on 2022-10-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitals_BP', '0004_alter_blood_pressure_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_pressure',
            name='comments',
            field=models.TextField(default=None, max_length=999),
        ),
    ]
